# Generated by Django 3.2 on 2021-04-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitedservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitedservice',
            options={'ordering': ('id',)},
        ),
    ]
