# Generated by Django 3.2 on 2021-04-27 21:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technicians_attention', models.CharField(max_length=200)),
                ('level_of_satisfaction', models.CharField(max_length=200)),
                ('request_services_again', models.CharField(max_length=200)),
                ('reccomend_to_others', models.CharField(max_length=200)),
                ('comments', models.CharField(max_length=1000)),
                ('technician_incharge', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_review', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
