# Generated by Django 3.2 on 2021-04-20 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200, unique=True)),
                ('second_name', models.CharField(max_length=200, unique=True)),
                ('last_name', models.CharField(max_length=200, unique=True)),
                ('mothers_last_name', models.CharField(max_length=200, unique=True)),
                ('street', models.CharField(max_length=1000, unique=True)),
                ('internal_number', models.IntegerField()),
                ('external_number', models.IntegerField()),
                ('cologne', models.CharField(max_length=1000, unique=True)),
                ('delegation_municipality', models.CharField(max_length=1000, unique=True)),
                ('town', models.CharField(max_length=1000, unique=True)),
                ('age', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('rfc', models.CharField(max_length=1000, unique=True)),
                ('email', models.EmailField(max_length=500)),
                ('nationality', models.CharField(max_length=1000, unique=True)),
                ('served_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='client_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
