# Generated by Django 3.2 on 2021-04-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_clientinformation_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientinformation',
            name='cologne',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='delegation_municipality',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='first_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='mothers_last_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='nationality',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='rfc',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='second_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='street',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='clientinformation',
            name='town',
            field=models.CharField(max_length=1000),
        ),
    ]
