# Generated by Django 3.2 on 2021-04-24 02:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210421_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientinformation',
            name='joindate',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 4, 24, 2, 7, 50, 220403, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
