# Generated by Django 3.2 on 2021-04-20 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehicledata',
            options={'ordering': ('-id',)},
        ),
    ]
