# Generated by Django 3.2 on 2021-04-22 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_data', '0002_alter_vehicledata_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledata',
            name='proposed_departure_date',
        ),
        migrations.RemoveField(
            model_name='vehicledata',
            name='vehicle_entry_date',
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='liters_of_gasoline',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='service_specification',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='solicited_service',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_brand',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_color',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_plate',
            field=models.CharField(max_length=200),
        ),
    ]
