# Generated by Django 3.2 on 2021-04-22 03:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_data', '0003_auto_20210422_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicledata',
            name='proposed_departure_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 3, 53, 5, 795955, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='vehicle_entry_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 22, 3, 53, 14, 710945, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
