# Generated by Django 3.2 on 2021-04-25 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitedservices', '0001_initial'),
        ('vehicle_data', '0004_auto_20210422_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='solicited_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicited_Vehicles', to='solicitedservices.solicitedservice'),
        ),
    ]
