# Generated by Django 3.2 on 2021-04-27 12:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_data', '0005_alter_vehicledata_solicited_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicledata',
            old_name='liters_of_gasoline',
            new_name='liters_of_gasoline_on_arrival',
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 4, 27, 12, 42, 14, 502354, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='actual_service_performed',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='liters_of_gasoline_on_departure',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('completed', 'completed')], default='pending', max_length=1000),
        ),
        migrations.AddField(
            model_name='vehicledata',
            name='vehicle_observation_on_departure',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_observation',
            field=models.CharField(max_length=1000),
        ),
    ]
