# Generated by Django 3.2 on 2021-04-27 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_data', '0006_auto_20210427_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicledata',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='actual_service_performed',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='liters_of_gasoline_on_departure',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='vehicledata',
            name='vehicle_observation_on_departure',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
