# Generated by Django 3.2 on 2021-04-25 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='authentication.roles'),
            preserve_default=False,
        ),
    ]
