# Generated by Django 3.2 on 2021-04-25 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phonenumber',
            field=models.IntegerField(default='0000000000', max_length=20),
            preserve_default=False,
        ),
    ]
